build_composer_project: false
build_composer: true
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/drupalvm"
drupal_core_path: "{{ drupal_composer_install_dir }}/src"
vagrant_hostname: composer.dev
vagrant_ip: 0.0.0.0
installed_extras:
  - adminer
  - blackfire
  - nodejs
  - drush
  - drupalconsole
  - redis
  - pimpmylog
