# Drupal config
drupal_build_composer_project: false
drupal_build_composer: false
drupal_composer_path: false
drupal_account_name: admin
drupal_account_pass: admin
drupal_install_profile: standard
drupalvm_webserver: nginx
drupal_composer_install_dir: /var/www/drupalvm
drupal_core_path: '{{ drupal_composer_install_dir }}/docroot'

configure_drush_aliases: true
configure_local_drush_aliases: true
installed_extras:
    - nodejs
    - drush
    - pimpmylog
    - adminer
    - redis
    - mailhog
    - drupalconsole

# Node JS
nodejs_version: 8.x

# PHP
php_max_input_vars: '4000'
php_memory_limit: "512M"
php_max_execution_time: "720"
php_max_input_time: "720"
php_upload_max_filesize: "200M"
php_post_max_size: "200M"
php_date_timezone: "Europe/Berlin"

# Setup NGINX
nginx_client_max_body_size: "300m"
nginx_server_names_hash_bucket_size: "255"

# Tune MySQL
mysql_innodb_flush_log_at_trx_commit: "2"
mysql_max_allowed_packet: "1024M"

vagrant_ip: 0.0.0.0
install_site: false

vagrant_hostname: reference.dev
vagrant_machine_name: reference.dev
